//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormulaTorneo
    {
        public FormulaTorneo()
        {
        }
    
        public int IDFormula { get; set; }
        public string Formula { get; set; }
        public string Descrizione { get; set; }
    }
}
