//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Impianto
    {
        public Impianto()
        {
        }
    
        public int IDImpianto { get; set; }
        public string IDComune { get; set; }
        public string NomeImpianto { get; set; }
        public int NumeroCampi { get; set; }
        public string Indirizzo { get; set; }
        public string CAP { get; set; }
        public string Descrizione { get; set; }
        public string Email { get; set; }
        public string Sito { get; set; }
        public string Tel { get; set; }

    }
}
