//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParametroQualita
    {
        public ParametroQualita()
        {
        }
    
        public int IDParametro { get; set; }
        public string NomeParametro { get; set; }
        public int ValoreParametro { get; set; }
    }
}
