//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partita
    {
        public int IDPartita { get; set; }
        public int IDSQ1 { get; set; }
        public int IDSQ2 { get; set; }
        public int IDArbitro1 { get; set; }
        public Nullable<int> IDArbitro2 { get; set; }
        public int IDTorneo { get; set; }
        public string Campo { get; set; }
        public System.DateTime DataPartita { get; set; }
        public System.TimeSpan OraPartita { get; set; }
        public int PT1S1 { get; set; }
        public int PT2S1 { get; set; }
        public int PT1S2 { get; set; }
        public int PT2S2 { get; set; }
        public int PT1S3 { get; set; }
        public int PT2S3 { get; set; }
    }
}
