//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoricoTessereAllenatori
    {
        public int IDAllenatore { get; set; }
        public Nullable<int> IDSocieta { get; set; }
        public string CodiceTessera { get; set; }
        public string TipoTessera { get; set; }
        public System.DateTime DataTesseramento { get; set; }
        public int AnnoTesseramento { get; set; }
        public Nullable<decimal> Importo { get; set; }
    }
}
