//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoTorneo
    {
        public TipoTorneo()
        {
        }
    
        public int IDTipoTorneo { get; set; }
        public string Descrizione { get; set; }
        public string Note { get; set; }
    }
}
