//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Torneo
    {
        public Torneo()
        {
        }
    
        public int IDTorneo { get; set; }
        public int IDTipoTorneo { get; set; }
        public int IDSupervisore { get; set; }
        public Nullable<int> IDSupervisoreArbitrale { get; set; }
        public Nullable<int> IDDirettoreCompetizione { get; set; }
        public int IDFormula { get; set; }
        public Nullable<decimal> QuotaIscrizione { get; set; }
        public int PuntiVittoria { get; set; }
        public decimal Montepremi { get; set; }
        public System.DateTime DataInizio { get; set; }
        public System.DateTime DataFine { get; set; }
        public string Gender { get; set; }
        public int NumTeamTabellone { get; set; }
        public int NumTeamQualifiche { get; set; }
    }
}
