DROP TABLE IF EXISTS Atleti;
DROP TABLE IF EXISTS Societa;
DROP TABLE IF EXISTS Comuni;

DROP TABLE IF EXISTS Utenti_Ruoli;
DROP TABLE IF EXISTS Utenti;

CREATE TABLE Comuni(
	Cod VARCHAR(4) NOT NULL PRIMARY KEY,
	Citta VARCHAR(50) NOT NULL,
    Provincia VARCHAR(3) NOT NULL,
    Regione VARCHAR(20) NOT NULL,
	SiglaProvincia VARCHAR(2) NOT NULL,
	SiglaRegione VARCHAR(2) NOT NULL
);

CREATE TABLE Societa(
	Societa_Id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	Comuni_Cod VARCHAR(4) NOT NULL,
	NomeSocieta VARCHAR(50) NOT NULL,
	Indirizzo VARCHAR(20) NOT NULL,	
	CAP VARCHAR(5),
	Email VARCHAR(50),
	Sito VARCHAR(50),
	FOREIGN KEY (Comuni_Cod) REFERENCES Comuni(Cod) 
);

CREATE TABLE Atleti(
	Atleti_Id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	Societa_Id INTEGER NOT NULL,
	CodiceTessera VARCHAR(20) NOT NULL,
	Nome VARCHAR(40) NOT NULL,
    Cognome VARCHAR(40) NOT NULL,
	Sesso CHAR,
	CodiceFiscale VARCHAR(20) NOT NULL,
	DataNascita date NOT NULL,
	Indirizzo VARCHAR(50),
	CAP VARCHAR(5),
	Email VARCHAR(50),
	Tel VARCHAR(20),
	FOREIGN KEY (Societa_Id) REFERENCES Societa(Societa_Id)
);

CREATE TABLE Utenti(
	Username VARCHAR(50) NOT NULL PRIMARY KEY,
	Password VARCHAR(50) NOT NULL 
);

CREATE TABLE Utenti_Ruoli(
	Username VARCHAR(50) NOT NULL,
	Ruolo VARCHAR(50) NOT NULL,
	PRIMARY KEY(Username, Ruolo)
	FOREIGN KEY (Username) REFERENCES Utenti(Username)
);